### ISSUE TITLE
mongo-cluster secure

### ISSUE THREAD

**Issue by appagithub** [minhhungit/mongodb-cluster-docker-compose#5]
how to make this mongodb-cluster-docker-compose  secured ?
something like this article : https://medium.com/@MaxouMask/secured-mongodb-container-6b602ef67885

**Comment by peterwillcn** [comment]
2020-04-21T14:53:17.085+0000 I CONTROL  [main] ** WARNING: Access control is not enabled for the database.
2020-04-21T14:53:17.085+0000 I CONTROL  [main] **          Read and write access to data and configuration is unrestricted.

**Comment by minhhungit** [comment]
that is because we don't setup authentication for the mongodb cluster, this docker compose is just designed for dev/test environment so authenticate is not really necessary , for production you should setup cluster by manual I think 

For production you guys might need to check this link for more information:

https://www.mongodb.com/docs/manual/tutorial/deploy-replica-set-with-keyfile-access-control/

**Comment by minhhungit** [comment]
Try with authentication config here https://github.com/minhhungit/mongodb-cluster-docker-compose/issues/8#issuecomment-1302870912
